using System.Text;

namespace PhotoIdentity.Docs;

public sealed class StatusGenerator
{
    private readonly RegistryStore _store;

    public StatusGenerator(RegistryStore store)
    {
        _store = store;
    }

    public bool Generate(
        RepositoryPaths paths,
        WorkItemRegistry workItems,
        MilestoneRegistry milestones,
        bool checkOnly,
        TextWriter output)
    {
        Dictionary<string, WorkItem> itemMap = workItems.WorkItems
            .ToDictionary(item => item.Id, StringComparer.Ordinal);

        foreach (Milestone milestone in milestones.Milestones)
        {
            milestone.Status = WorkItemRules.CalculateMilestoneStatus(milestone, itemMap);
        }

        string roadmap = BuildRoadmap(milestones);
        string? currentWorkItems = null;
        string? workItemsIndex = null;
        if (paths.HasShardedWorkItemStore)
        {
            currentWorkItems = BuildCurrentWorkItemsView(workItems);
            workItemsIndex = BuildWorkItemsIndex(workItems);
        }

        if (checkOnly)
        {
            bool current = CheckFile(paths.Roadmap, roadmap, output);
            if (currentWorkItems is not null && workItemsIndex is not null)
            {
                current &= CheckFile(paths.WorkItemsRegistry, currentWorkItems, output);
                current &= CheckFile(paths.WorkItemsIndex, workItemsIndex, output);
            }

            return current;
        }

        _store.SaveMilestones(paths, milestones);
        RegistryStore.WriteAtomically(paths.Roadmap, roadmap);
        if (currentWorkItems is not null && workItemsIndex is not null)
        {
            RegistryStore.WriteAtomically(paths.WorkItemsRegistry, currentWorkItems);
            RegistryStore.WriteAtomically(paths.WorkItemsIndex, workItemsIndex);
            output.WriteLine(
                "Generated milestone statuses, roadmap.md, bounded work-items.yaml and work-items-index.md.");
        }
        else
        {
            output.WriteLine("Generated milestone statuses and roadmap.md.");
        }

        return true;
    }

    private string BuildCurrentWorkItemsView(WorkItemRegistry workItems)
    {
        WorkItemRegistry current = new()
        {
            SchemaVersion = workItems.SchemaVersion,
            AllowedStatuses = [.. workItems.AllowedStatuses],
            WorkItems = workItems.WorkItems
                .Where(item => !IsTerminal(item.Status))
                .OrderBy(item => item.Id, StringComparer.Ordinal)
                .ToList(),
        };

        return "# Generated from canonical work-item shards. Do not edit; use PhotoIdentity.Docs lifecycle commands.\n"
            + _store.SerializeWorkItemRegistry(current);
    }

    private static string BuildWorkItemsIndex(WorkItemRegistry workItems)
    {
        List<WorkItem> current = workItems.WorkItems
            .Where(item => !IsTerminal(item.Status))
            .OrderBy(item => item.Id, StringComparer.Ordinal)
            .ToList();
        int terminalCount = workItems.WorkItems.Count - current.Count;

        StringBuilder builder = new();
        builder.AppendLine("# Work-item status index");
        builder.AppendLine();
        builder.AppendLine(
            "Generated from canonical per-item YAML under [`work-items/`](work-items/). Do not edit this file manually.");
        builder.AppendLine();
        builder.AppendLine($"Current work items: **{current.Count}**. Archived terminal items: **{terminalCount}**.");
        builder.AppendLine();
        builder.AppendLine("| Work item | Milestone | Status | Owner | Canonical status |");
        builder.AppendLine("|---|---|---|---|---|");
        foreach (WorkItem item in current)
        {
            builder.AppendLine(
                $"| [{item.Id}]({item.Document}) {EscapeTable(item.Title)} | {item.Milestone} | {item.Status} | {EscapeTable(item.Owner)} | [YAML](work-items/active/{item.Id}.yaml) |");
        }

        builder.AppendLine();
        builder.AppendLine("Historical items stay queryable without opening the archive directory:");
        builder.AppendLine();
        builder.AppendLine("```powershell");
        builder.AppendLine("dotnet run --project tools/PhotoIdentity.Docs -- show WI-0057");
        builder.AppendLine("```");
        builder.AppendLine();
        builder.AppendLine(
            "Use `PhotoIdentity.Docs next` for ready work and the lifecycle commands for status changes; `work-items.yaml` is only a generated current-work compatibility view.");

        return builder.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private static bool CheckFile(string path, string expected, TextWriter output)
    {
        string actual = File.Exists(path)
            ? File.ReadAllText(path).Replace("\r\n", "\n", StringComparison.Ordinal)
            : "";

        if (actual == expected)
        {
            return true;
        }

        output.WriteLine($"Generated file is stale: {path}");
        return false;
    }

    private static string BuildRoadmap(MilestoneRegistry milestones)
    {
        StringBuilder builder = new();
        builder.AppendLine("# Roadmap");
        builder.AppendLine();
        builder.AppendLine("Generated from [`status/milestones.yaml`](status/milestones.yaml). Do not edit the table manually.");
        builder.AppendLine();
        builder.AppendLine("| Milestone | Outcome | Current status |");
        builder.AppendLine("|---|---|---|");
        foreach (Milestone milestone in milestones.Milestones)
        {
            builder.AppendLine($"| {milestone.Id} | {milestone.Title} | {milestone.Status} |");
        }

        builder.AppendLine();
        builder.AppendLine("Expected evolution:");
        builder.AppendLine();
        builder.AppendLine("```text");
        builder.AppendLine("0.x local inference, review, model evaluation and archive-readiness foundations");
        builder.AppendLine("1.0 permanent catalogue ready to begin processing the real full archive");
        builder.AppendLine("post-1.0 complete archive coverage and ongoing synchronisation");
        builder.AppendLine("post-1.0 improve identity automation and operator experience");
        builder.AppendLine("later add capture metadata, location and semantic library intelligence");
        builder.AppendLine("```");

        return builder.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private static string EscapeTable(string value) =>
        value.Replace("|", "\\|", StringComparison.Ordinal);

    private static bool IsTerminal(string status) =>
        status is "completed" or "cancelled";
}
