using Npgsql;
using NpgsqlTypes;
using PhotoIdentity.Core.Identifiers;
using PhotoIdentity.Core.People;

namespace PhotoIdentity.Persistence.Postgres;

public sealed class PostgresPersonFamilyMetadataRepository : IPersonFamilyMetadataRepository
{
    private readonly PostgresCatalogueDatabase _database;

    public PostgresPersonFamilyMetadataRepository(PostgresCatalogueDatabase database)
    {
        ArgumentNullException.ThrowIfNull(database);
        _database = database;
    }

    public static async Task EnsureSchemaAsync(
        PostgresCatalogueDatabase database,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(database);
        await using NpgsqlConnection connection = await database.OpenConnectionAsync(cancellationToken);
        await using NpgsqlCommand command = connection.CreateCommand();
        command.CommandText = """
            CREATE TABLE IF NOT EXISTS person_birth_metadata (
                person_id uuid NOT NULL PRIMARY KEY,
                precision text NOT NULL CHECK (precision IN ('year', 'month', 'day')),
                birth_year smallint NOT NULL CHECK (birth_year BETWEEN 1 AND 9999),
                birth_month smallint NULL CHECK (birth_month IS NULL OR birth_month BETWEEN 1 AND 12),
                birth_day smallint NULL CHECK (birth_day IS NULL OR birth_day BETWEEN 1 AND 31),
                actor text NOT NULL CHECK (btrim(actor) <> ''),
                updated_at_utc timestamp with time zone NOT NULL,
                CONSTRAINT fk_person_birth_metadata_person
                    FOREIGN KEY (person_id) REFERENCES people (id) ON DELETE CASCADE,
                CHECK (
                    (precision = 'year' AND birth_month IS NULL AND birth_day IS NULL)
                    OR (precision = 'month' AND birth_month IS NOT NULL AND birth_day IS NULL)
                    OR (precision = 'day' AND birth_month IS NOT NULL AND birth_day IS NOT NULL))
            );

            CREATE TABLE IF NOT EXISTS person_relationships (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                source_person_id uuid NOT NULL,
                target_person_id uuid NOT NULL,
                relationship_kind text NOT NULL CHECK (relationship_kind IN ('parent', 'spouse', 'sibling', 'grandparent')),
                actor text NOT NULL CHECK (btrim(actor) <> ''),
                created_at_utc timestamp with time zone NOT NULL,
                CONSTRAINT fk_person_relationship_source
                    FOREIGN KEY (source_person_id) REFERENCES people (id) ON DELETE CASCADE,
                CONSTRAINT fk_person_relationship_target
                    FOREIGN KEY (target_person_id) REFERENCES people (id) ON DELETE CASCADE,
                CHECK (source_person_id <> target_person_id),
                UNIQUE (source_person_id, target_person_id, relationship_kind)
            );

            CREATE INDEX IF NOT EXISTS ix_person_relationships_target
                ON person_relationships (target_person_id, relationship_kind, source_person_id);

            CREATE UNIQUE INDEX IF NOT EXISTS ux_person_relationships_symmetric
                ON person_relationships (
                    LEAST(source_person_id, target_person_id),
                    GREATEST(source_person_id, target_person_id),
                    relationship_kind)
                WHERE relationship_kind IN ('spouse', 'sibling');

            CREATE OR REPLACE FUNCTION photo_identity_move_family_metadata_after_merge()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $function$
            BEGIN
                IF OLD.merged_into_person_id IS NULL
                   AND NEW.merged_into_person_id IS NOT NULL THEN
                    INSERT INTO person_birth_metadata (
                        person_id,
                        precision,
                        birth_year,
                        birth_month,
                        birth_day,
                        actor,
                        updated_at_utc)
                    SELECT
                        NEW.merged_into_person_id,
                        source.precision,
                        source.birth_year,
                        source.birth_month,
                        source.birth_day,
                        source.actor,
                        source.updated_at_utc
                    FROM person_birth_metadata AS source
                    WHERE source.person_id = NEW.id
                    ON CONFLICT (person_id) DO NOTHING;

                    DELETE FROM person_birth_metadata
                    WHERE person_id = NEW.id;

                    INSERT INTO person_relationships (
                        source_person_id,
                        target_person_id,
                        relationship_kind,
                        actor,
                        created_at_utc)
                    SELECT
                        CASE
                            WHEN relationship_kind IN ('spouse', 'sibling') THEN
                                LEAST(
                                    CASE WHEN source_person_id = NEW.id THEN NEW.merged_into_person_id ELSE source_person_id END,
                                    CASE WHEN target_person_id = NEW.id THEN NEW.merged_into_person_id ELSE target_person_id END)
                            ELSE CASE WHEN source_person_id = NEW.id THEN NEW.merged_into_person_id ELSE source_person_id END
                        END,
                        CASE
                            WHEN relationship_kind IN ('spouse', 'sibling') THEN
                                GREATEST(
                                    CASE WHEN source_person_id = NEW.id THEN NEW.merged_into_person_id ELSE source_person_id END,
                                    CASE WHEN target_person_id = NEW.id THEN NEW.merged_into_person_id ELSE target_person_id END)
                            ELSE CASE WHEN target_person_id = NEW.id THEN NEW.merged_into_person_id ELSE target_person_id END
                        END,
                        relationship_kind,
                        actor,
                        created_at_utc
                    FROM person_relationships
                    WHERE (source_person_id = NEW.id OR target_person_id = NEW.id)
                      AND (CASE WHEN source_person_id = NEW.id THEN NEW.merged_into_person_id ELSE source_person_id END)
                          <> (CASE WHEN target_person_id = NEW.id THEN NEW.merged_into_person_id ELSE target_person_id END)
                    ON CONFLICT DO NOTHING;

                    DELETE FROM person_relationships
                    WHERE source_person_id = NEW.id OR target_person_id = NEW.id;
                END IF;

                RETURN NEW;
            END;
            $function$;

            DO $block$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_trigger
                    WHERE tgname = 'trg_person_family_metadata_after_merge') THEN
                    CREATE TRIGGER trg_person_family_metadata_after_merge
                        AFTER UPDATE OF merged_into_person_id ON people
                        FOR EACH ROW
                        EXECUTE FUNCTION photo_identity_move_family_metadata_after_merge();
                END IF;
            END;
            $block$;
            """;
        await command.ExecuteNonQueryAsync(cancellationToken);
    }

    public async Task<PersonFamilyMetadata> GetAsync(
        PersonId personId,
        CancellationToken cancellationToken = default)
    {
        await EnsureSchemaAsync(_database, cancellationToken);
        await using NpgsqlConnection connection = await _database.OpenConnectionAsync(cancellationToken);
        await RequireActivePersonAsync(connection, personId, cancellationToken);

        PersonBirthDate? birthDate = null;
        await using (NpgsqlCommand birth = connection.CreateCommand())
        {
            birth.CommandText = """
                SELECT precision, birth_year, birth_month, birth_day
                FROM person_birth_metadata
                WHERE person_id = @person_id;
                """;
            birth.Parameters.AddWithValue("person_id", NpgsqlDbType.Uuid, personId.Value);
            await using NpgsqlDataReader reader = await birth.ExecuteReaderAsync(cancellationToken);
            if (await reader.ReadAsync(cancellationToken))
            {
                birthDate = new PersonBirthDate(
                    reader.GetInt16(1),
                    reader.IsDBNull(2) ? null : reader.GetInt16(2),
                    reader.IsDBNull(3) ? null : reader.GetInt16(3),
                    reader.GetString(0));
            }
        }

        List<PersonFamilyRelationship> relationships = [];
        await using (NpgsqlCommand relationship = connection.CreateCommand())
        {
            relationship.CommandText = """
                SELECT
                    relationship.id,
                    relationship.source_person_id,
                    relationship.target_person_id,
                    relationship.relationship_kind,
                    relationship.actor,
                    relationship.created_at_utc,
                    source.display_name,
                    target.display_name
                FROM person_relationships AS relationship
                INNER JOIN people AS source ON source.id = relationship.source_person_id
                INNER JOIN people AS target ON target.id = relationship.target_person_id
                WHERE relationship.source_person_id = @person_id
                   OR relationship.target_person_id = @person_id
                ORDER BY relationship.relationship_kind, relationship.id;
                """;
            relationship.Parameters.AddWithValue("person_id", NpgsqlDbType.Uuid, personId.Value);
            await using NpgsqlDataReader reader = await relationship.ExecuteReaderAsync(cancellationToken);
            while (await reader.ReadAsync(cancellationToken))
            {
                PersonId sourceId = PersonId.From(reader.GetGuid(1));
                bool selectedIsSource = sourceId == personId;
                PersonId relatedId = PersonId.From(reader.GetGuid(selectedIsSource ? 2 : 1));
                string storedKind = reader.GetString(3);
                relationships.Add(new PersonFamilyRelationship(
                    reader.GetInt64(0),
                    personId,
                    relatedId,
                    reader.GetString(selectedIsSource ? 7 : 6),
                    selectedIsSource ? storedKind : PersonRelationshipKinds.Inverse(storedKind),
                    reader.GetString(4),
                    reader.GetFieldValue<DateTimeOffset>(5)));
            }
        }

        return new PersonFamilyMetadata(personId, birthDate, relationships);
    }

    public async Task SetBirthDateAsync(
        PersonId personId,
        PersonBirthDate? birthDate,
        string actor,
        DateTimeOffset changedAtUtc,
        CancellationToken cancellationToken = default)
    {
        string normalizedActor = Required(actor, nameof(actor));
        await EnsureSchemaAsync(_database, cancellationToken);
        await using NpgsqlConnection connection = await _database.OpenConnectionAsync(cancellationToken);
        await RequireActivePersonAsync(connection, personId, cancellationToken);

        await using NpgsqlCommand command = connection.CreateCommand();
        if (birthDate is null)
        {
            command.CommandText = "DELETE FROM person_birth_metadata WHERE person_id = @person_id;";
            command.Parameters.AddWithValue("person_id", NpgsqlDbType.Uuid, personId.Value);
        }
        else
        {
            command.CommandText = """
                INSERT INTO person_birth_metadata (
                    person_id, precision, birth_year, birth_month, birth_day, actor, updated_at_utc)
                VALUES (
                    @person_id, @precision, @birth_year, @birth_month, @birth_day, @actor, @updated_at_utc)
                ON CONFLICT (person_id) DO UPDATE
                SET precision = EXCLUDED.precision,
                    birth_year = EXCLUDED.birth_year,
                    birth_month = EXCLUDED.birth_month,
                    birth_day = EXCLUDED.birth_day,
                    actor = EXCLUDED.actor,
                    updated_at_utc = EXCLUDED.updated_at_utc;
                """;
            command.Parameters.AddWithValue("person_id", NpgsqlDbType.Uuid, personId.Value);
            command.Parameters.AddWithValue("precision", NpgsqlDbType.Text, birthDate.Precision);
            command.Parameters.AddWithValue("birth_year", NpgsqlDbType.Smallint, checked((short)birthDate.Year));
            command.Parameters.Add("birth_month", NpgsqlDbType.Smallint).Value =
                birthDate.Month is int month ? checked((short)month) : DBNull.Value;
            command.Parameters.Add("birth_day", NpgsqlDbType.Smallint).Value =
                birthDate.Day is int day ? checked((short)day) : DBNull.Value;
            command.Parameters.AddWithValue("actor", NpgsqlDbType.Text, normalizedActor);
            command.Parameters.AddWithValue("updated_at_utc", NpgsqlDbType.TimestampTz, changedAtUtc.ToUniversalTime());
        }

        await command.ExecuteNonQueryAsync(cancellationToken);
    }

    public async Task<PersonFamilyRelationship> AddRelationshipAsync(
        PersonId personId,
        PersonId relatedPersonId,
        string kind,
        string actor,
        DateTimeOffset createdAtUtc,
        CancellationToken cancellationToken = default)
    {
        if (personId == relatedPersonId)
        {
            throw new ArgumentException("A person cannot have a family relationship to themselves.", nameof(relatedPersonId));
        }

        string normalizedKind = PersonRelationshipKinds.Normalize(kind);
        string normalizedActor = Required(actor, nameof(actor));
        (PersonId sourceId, PersonId targetId, string storedKind) = CanonicalStorage(personId, relatedPersonId, normalizedKind);

        await EnsureSchemaAsync(_database, cancellationToken);
        await using NpgsqlConnection connection = await _database.OpenConnectionAsync(cancellationToken);
        await RequireActivePersonAsync(connection, personId, cancellationToken);
        await RequireActivePersonAsync(connection, relatedPersonId, cancellationToken);

        await using NpgsqlCommand command = connection.CreateCommand();
        command.CommandText = """
            INSERT INTO person_relationships (
                source_person_id, target_person_id, relationship_kind, actor, created_at_utc)
            VALUES (@source_person_id, @target_person_id, @relationship_kind, @actor, @created_at_utc)
            ON CONFLICT DO NOTHING
            RETURNING id;
            """;
        command.Parameters.AddWithValue("source_person_id", NpgsqlDbType.Uuid, sourceId.Value);
        command.Parameters.AddWithValue("target_person_id", NpgsqlDbType.Uuid, targetId.Value);
        command.Parameters.AddWithValue("relationship_kind", NpgsqlDbType.Text, storedKind);
        command.Parameters.AddWithValue("actor", NpgsqlDbType.Text, normalizedActor);
        command.Parameters.AddWithValue("created_at_utc", NpgsqlDbType.TimestampTz, createdAtUtc.ToUniversalTime());

        object? result = await command.ExecuteScalarAsync(cancellationToken);
        if (result is null)
        {
            PersonFamilyMetadata existing = await GetAsync(personId, cancellationToken);
            PersonFamilyRelationship? match = existing.Relationships.FirstOrDefault(item =>
                item.RelatedPersonId == relatedPersonId && item.Kind == normalizedKind);
            return match ?? throw new InvalidOperationException("The family relationship already exists but could not be resolved.");
        }

        long id = Convert.ToInt64(result, System.Globalization.CultureInfo.InvariantCulture);
        PersonFamilyMetadata metadata = await GetAsync(personId, cancellationToken);
        return metadata.Relationships.Single(item => item.Id == id);
    }

    public async Task<bool> DeleteRelationshipAsync(
        PersonId personId,
        long relationshipId,
        CancellationToken cancellationToken = default)
    {
        if (relationshipId <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(relationshipId));
        }

        await EnsureSchemaAsync(_database, cancellationToken);
        await using NpgsqlConnection connection = await _database.OpenConnectionAsync(cancellationToken);
        await RequireActivePersonAsync(connection, personId, cancellationToken);
        await using NpgsqlCommand command = connection.CreateCommand();
        command.CommandText = """
            DELETE FROM person_relationships
            WHERE id = @id
              AND (source_person_id = @person_id OR target_person_id = @person_id);
            """;
        command.Parameters.AddWithValue("id", NpgsqlDbType.Bigint, relationshipId);
        command.Parameters.AddWithValue("person_id", NpgsqlDbType.Uuid, personId.Value);
        return await command.ExecuteNonQueryAsync(cancellationToken) > 0;
    }

    private static (PersonId Source, PersonId Target, string Kind) CanonicalStorage(
        PersonId personId,
        PersonId relatedPersonId,
        string kind)
    {
        if (kind == PersonRelationshipKinds.Child)
        {
            return (relatedPersonId, personId, PersonRelationshipKinds.Parent);
        }

        if (kind == PersonRelationshipKinds.Grandchild)
        {
            return (relatedPersonId, personId, PersonRelationshipKinds.Grandparent);
        }

        if (kind is PersonRelationshipKinds.Spouse or PersonRelationshipKinds.Sibling &&
            string.CompareOrdinal(personId.ToString(), relatedPersonId.ToString()) > 0)
        {
            return (relatedPersonId, personId, kind);
        }

        return (personId, relatedPersonId, kind);
    }

    private static async Task RequireActivePersonAsync(
        NpgsqlConnection connection,
        PersonId personId,
        CancellationToken cancellationToken)
    {
        await using NpgsqlCommand command = connection.CreateCommand();
        command.CommandText = """
            SELECT 1
            FROM people
            WHERE id = @person_id
              AND merged_into_person_id IS NULL
              AND display_name IS NOT NULL
              AND btrim(display_name) <> '';
            """;
        command.Parameters.AddWithValue("person_id", NpgsqlDbType.Uuid, personId.Value);
        if (await command.ExecuteScalarAsync(cancellationToken) is null)
        {
            throw new KeyNotFoundException($"Active person {personId} was not found.");
        }
    }

    private static string Required(string value, string parameterName)
    {
        string normalized = value?.Trim() ?? string.Empty;
        if (normalized.Length is < 1 or > 200)
        {
            throw new ArgumentException("The value must contain between 1 and 200 characters.", parameterName);
        }

        return normalized;
    }
}
