namespace PhotoIdentity.Persistence.Postgres;

internal static class PostgresPersonFamilyMetadataSchema
{
    internal const string Sql = """
        CREATE TABLE IF NOT EXISTS person_birth_metadata (
            person_id uuid NOT NULL PRIMARY KEY,
            precision text NOT NULL CHECK (precision IN ('year', 'month', 'day')),
            birth_year smallint NOT NULL CHECK (birth_year BETWEEN 1 AND 9999),
            birth_month smallint NULL CHECK (birth_month IS NULL OR birth_month BETWEEN 1 AND 12),
            birth_day smallint NULL CHECK (birth_day IS NULL OR birth_day BETWEEN 1 AND 31),
            actor text NOT NULL CHECK (btrim(actor) <> ''),
            updated_at_utc timestamp with time zone NOT NULL,
            CONSTRAINT fk_person_birth_metadata_person
                FOREIGN KEY (person_id) REFERENCES people (id) ON DELETE CASCADE,
            CHECK (
                (precision = 'year' AND birth_month IS NULL AND birth_day IS NULL)
                OR (precision = 'month' AND birth_month IS NOT NULL AND birth_day IS NULL)
                OR (precision = 'day' AND birth_month IS NOT NULL AND birth_day IS NOT NULL))
        );

        CREATE TABLE IF NOT EXISTS person_relationships (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_person_id uuid NOT NULL,
            target_person_id uuid NOT NULL,
            relationship_kind text NOT NULL CHECK (relationship_kind IN ('parent', 'spouse', 'sibling', 'grandparent')),
            actor text NOT NULL CHECK (btrim(actor) <> ''),
            created_at_utc timestamp with time zone NOT NULL,
            CONSTRAINT fk_person_relationship_source
                FOREIGN KEY (source_person_id) REFERENCES people (id) ON DELETE CASCADE,
            CONSTRAINT fk_person_relationship_target
                FOREIGN KEY (target_person_id) REFERENCES people (id) ON DELETE CASCADE,
            CHECK (source_person_id <> target_person_id),
            UNIQUE (source_person_id, target_person_id, relationship_kind)
        );

        CREATE INDEX IF NOT EXISTS ix_person_relationships_target
            ON person_relationships (target_person_id, relationship_kind, source_person_id);

        CREATE UNIQUE INDEX IF NOT EXISTS ux_person_relationships_symmetric
            ON person_relationships (
                LEAST(source_person_id, target_person_id),
                GREATEST(source_person_id, target_person_id),
                relationship_kind)
            WHERE relationship_kind IN ('spouse', 'sibling');

        CREATE OR REPLACE FUNCTION photo_identity_move_family_metadata_after_merge()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $function$
        BEGIN
            IF OLD.merged_into_person_id IS NULL
               AND NEW.merged_into_person_id IS NOT NULL THEN
                INSERT INTO person_birth_metadata (
                    person_id,
                    precision,
                    birth_year,
                    birth_month,
                    birth_day,
                    actor,
                    updated_at_utc)
                SELECT
                    NEW.merged_into_person_id,
                    source.precision,
                    source.birth_year,
                    source.birth_month,
                    source.birth_day,
                    source.actor,
                    source.updated_at_utc
                FROM person_birth_metadata AS source
                WHERE source.person_id = NEW.id
                ON CONFLICT (person_id) DO NOTHING;

                DELETE FROM person_birth_metadata
                WHERE person_id = NEW.id;

                INSERT INTO person_relationships (
                    source_person_id,
                    target_person_id,
                    relationship_kind,
                    actor,
                    created_at_utc)
                SELECT
                    CASE
                        WHEN relationship_kind IN ('spouse', 'sibling') THEN
                            LEAST(
                                CASE WHEN source_person_id = NEW.id THEN NEW.merged_into_person_id ELSE source_person_id END,
                                CASE WHEN target_person_id = NEW.id THEN NEW.merged_into_person_id ELSE target_person_id END)
                        ELSE CASE WHEN source_person_id = NEW.id THEN NEW.merged_into_person_id ELSE source_person_id END
                    END,
                    CASE
                        WHEN relationship_kind IN ('spouse', 'sibling') THEN
                            GREATEST(
                                CASE WHEN source_person_id = NEW.id THEN NEW.merged_into_person_id ELSE source_person_id END,
                                CASE WHEN target_person_id = NEW.id THEN NEW.merged_into_person_id ELSE target_person_id END)
                        ELSE CASE WHEN target_person_id = NEW.id THEN NEW.merged_into_person_id ELSE target_person_id END
                    END,
                    relationship_kind,
                    actor,
                    created_at_utc
                FROM person_relationships
                WHERE (source_person_id = NEW.id OR target_person_id = NEW.id)
                  AND (CASE WHEN source_person_id = NEW.id THEN NEW.merged_into_person_id ELSE source_person_id END)
                      <> (CASE WHEN target_person_id = NEW.id THEN NEW.merged_into_person_id ELSE target_person_id END)
                ON CONFLICT DO NOTHING;

                DELETE FROM person_relationships
                WHERE source_person_id = NEW.id OR target_person_id = NEW.id;
            END IF;

            RETURN NEW;
        END;
        $function$;

        DO $block$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_trigger
                WHERE tgname = 'trg_person_family_metadata_after_merge') THEN
                CREATE TRIGGER trg_person_family_metadata_after_merge
                    AFTER UPDATE OF merged_into_person_id ON people
                    FOR EACH ROW
                    EXECUTE FUNCTION photo_identity_move_family_metadata_after_merge();
            END IF;
        END;
        $block$;
        """;
}
