<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../PhotoIdentity.Core/PhotoIdentity.Core.csproj" />
    <ProjectReference Include="../PhotoIdentity.Transfer.Bundles/PhotoIdentity.Transfer.Bundles.csproj" />
  </ItemGroup>
</Project>
